version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            -   8098:80
        depends_on:
            -   fpm
        volumes:
            - ./:/var/www/laravel-docker
        networks:
            - laravel-network

    fpm:
        build:
            args:
                UID: 1000
                GID: 1000
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            -   ./:/var/www/laravel-docker
        depends_on:
            -   pgsql
            -   rabbitmq
        networks:
            - laravel-network

    pgsql:
        image: postgres
        ports:
            -   5432:5432
        container_name: postgresdb
        restart: always
        env_file:
                - ./.env
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=127.0.0.1
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=agr
        networks:
            - laravel-network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
        - laravel-network

networks:
    laravel-network:
        driver: bridge